/* ─── Roker Labs · content store ───
   Bilingual (es-AR) content with country-specific swaps.
   AR (default) and PY share the same shape; the consumer reads
   from window.CONTENT[country].
   ─────────────────────────────────────── */
window.CATEGORIES = [
  {
    id: "tactica",
    label: "Operación táctica",
    short: "Operación",
    desc: "POS, catálogo, facturación, cobros y cuenta corriente. Todo lo que ocurre en el mostrador y en la conciliación diaria.",
    icon: "receipt",
  },
  {
    id: "ai",
    label: "Automatización inteligente",
    short: "Automatización",
    desc: "Dashboards, agentes IA por WhatsApp y procesos que dejan de pasar por manos. Donde la operación deja de escalar con headcount.",
    icon: "pulse",
  },
  {
    id: "infra",
    label: "Infraestructura",
    short: "Infraestructura",
    desc: "Hosting, soporte y los procesos que cuidan que nada se rompa el lunes a la mañana.",
    icon: "gear",
  },
];

window.CONTENT = {
  AR: {
    flag: "🇦🇷",
    code: "AR",
    label: "Argentina",
    hero: {
      eyebrowDot: "Operativo · AR + PY",
      eyebrow: "Software a medida · Roker Labs",
      h1Pre: "Sistemas que",
      h1Strike: "no se rompen los lunes",
      h1Post: "ni te dejan",
      h1Accent: "esperando un mes.",
      sub: "POS, ERPs, dashboards, integraciones AFIP y automatizaciones con IA. Una sola persona técnica, entrega total — hablás conmigo, decidís con vos, sin proxies.",
      cta1: "Agendar demo",
      cta2: "Ver demos",
      kpis: [
        { v: "15+", l: "años en operaciones" },
        { v: "4", l: "demos navegables" },
        { v: "AR·PY", l: "mercado dual" },
      ],
    },
    trust: {
      label: "Verticales en producción",
      items: [
        { name: "Retail electrónico", city: "Provincia BA", initial: "RT", color: "rgba(220,38,38,0.40)" },
        { name: "Distribución mayorista", city: "AMBA", initial: "DM", color: "rgba(96,165,250,0.30)" },
        { name: "Servicio técnico", city: "Norte AR", initial: "ST", color: "rgba(245,158,11,0.30)" },
        { name: "E-commerce + marketplaces", city: "CABA", initial: "EC", color: "rgba(16,185,129,0.30)" },
      ],
      stats: [
        { v: "$ 240M", l: "Procesado / año" },
        { v: "99.97%", l: "Uptime POS" },
      ],
    },
    bento: {
      eyebrow: "Lo que construyo",
      h2: "Software a medida. Una sola persona. Cero intermediarios.",
      sub: "Desde el POS que corre en el mostrador hasta el agente de IA que te contesta en WhatsApp. Todo configurado para tu operación, no para una demo genérica.",
    },
    services: [
      {
        id: "pos",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #2a1810, #08080b)",
        demoUrl: "https://saborcriollo-demo.pages.dev/",
        icon: "receipt",
        title: "Sistemas POS a medida",
        desc: "Mostrador rápido, cuenta corriente, listas de precios, cierre de caja. Toca y vendes.",
        price: "Desde USD 1.490",
        priceNote: "Setup",
        tag: "Demo en vivo",
        size: "w3 h2",
        brand: true,
        mock: "pos",
      },
      {
        id: "dash",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0f1922, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/dashboard-comando",
        icon: "pulse",
        title: "Dashboards de gestión",
        desc: "Lo que vendiste, lo que cobraste, lo que falta. Sin Excel, sin Looker, sin lag.",
        price: "Desde USD 690",
        priceNote: "Mensual",
        size: "w3 h2",
        mock: "dash",
      },
      {
        id: "ai-wa",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #182028, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/atajo-ia",
        icon: "whatsapp",
        title: "Agente IA por WhatsApp",
        desc: "Consultá stock, generá presupuesto, derivá al humano cuando hace falta.",
        price: "USD 290",
        priceNote: "/ mes",
        tag: "IA",
        size: "w2",
        mock: "chat",
      },
      {
        id: "catalog",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1e1a2b, #08080b)",
        demoUrl: "https://carhub-demo.pages.dev/",
        icon: "cart",
        title: "Catálogos web + WhatsApp",
        desc: "El cliente arma su pedido y te llega al WhatsApp, listo para confirmar.",
        price: "USD 890",
        size: "w2",
        mock: "catalog",
      },
      {
        id: "facturacion",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1a1815, #08080b)",
        demoUrl: "https://saborcriollo-demo.pages.dev/",
        liveLog: ["[14:32] CAE 75348230498234 emitido","[14:32] Factura B-00045821 · $ 12.450","[14:33] Respuesta AFIP · OK","[14:33] PDF enviado por email al cliente"],
        icon: "shield-check",
        title: "Facturación electrónica AFIP",
        desc: "Web Service homologado. Factura A, B, C, E y NC. Sin clicks raros.",
        size: "w2",
      },
      {
        id: "ml",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1d1916, #08080b)",
        demoUrl: "https://fixmobile-demo.pages.dev/",
        liveLog: ["[14:35] Stock A54 ×142 sincronizado","[14:35] 3 preguntas nuevas en ML-MLA-2348","[14:36] Venta confirmada · $ 34.500","[14:36] Etiqueta de envío generada"],
        icon: "box",
        title: "Integración MercadoLibre",
        desc: "Stock unificado, publicaciones, preguntas y ventas en un solo lugar.",
        size: "w2",
      },
      {
        id: "mp",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1556742205-e10c9486e506?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #161d24, #08080b)",
        demoUrl: "https://saborcriollo-demo.pages.dev/",
        liveLog: ["[14:38] QR Mercado Pago generado","[14:38] Pago confirmado · $ 24.300","[14:39] Acreditado en cuenta Galicia","[14:39] Recibo enviado por WhatsApp"],
        icon: "wallet",
        title: "Cobros Mercado Pago",
        desc: "Multi-cuenta, conciliación automática, QR, link y point físico.",
        size: "w2 h2",
      },
      {
        id: "ctacte",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1c1814, #08080b)",
        demoUrl: "https://fixmobile-demo.pages.dev/",
        liveLog: ["[14:40] Cliente mayorista · saldo +$ 48.500","[14:40] Pago parcial recibido · $ 18.000","[14:41] Recordatorio enviado a 3 clientes","[14:41] Mora calculada · 22 cuentas"],
        icon: "user",
        title: "Cuentas corrientes",
        desc: "Saldos, cobranzas, intereses, alertas. Diseñado con cobradoras reales.",
        size: "w2",
      },
      {
        id: "listas",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #131a22, #08080b)",
        demoUrl: "https://motohub-demo.pages.dev/",
        liveLog: ["[14:42] USD oficial: 1.490 · CCL: 1.612","[14:42] 142 SKUs recalculados","[14:43] Margen promedio · 38.2%","[14:43] Lista pública publicada"],
        icon: "receipt",
        title: "Listas de precios dinámicas",
        desc: "USD, costo, margen por categoría. Recalculá toda la lista en un click.",
        size: "w2",
      },
      {
        id: "migra",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #181b22, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/migra-excel",
        liveLog: ["[14:44] stock_marzo.xlsx · 8.432 filas","[14:44] 23 outliers detectados","[14:45] Base normalizada · 8.409 filas","[14:45] Reporte PDF listo · 12 páginas"],
        icon: "arrow-right",
        title: "Migraciones de Excel",
        desc: "Pasame tu planilla con 8000 SKUs. Te devuelvo la base normalizada en 48hs.",
        size: "w2",
      },
      {
        id: "soporte",
        cat: "infra",
        bgImage: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1c1820, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/soporte-directo",
        liveLog: ["[14:46] Mensaje recibido · cliente activo","[14:46] Sergio escribiendo…","[14:47] Llamada activa · 2:34 en vivo","[14:47] Issue resuelto · cerrado"],
        icon: "lock",
        title: "Soporte directo · sin tickets",
        desc: "WhatsApp directo conmigo. Si algo se rompe, lo arreglo. Sin call center.",
        size: "w2",
      },
      {
        id: "infra",
        cat: "infra",
        bgImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0e1620, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/infra-llave-mano",
        liveLog: ["[14:48] Healthcheck · 99.99% uptime","[14:48] Postgres replicado · 0 lag","[14:49] Backup diario completado · 1.4 GB","[14:49] Cloudflare cache HIT 94.2%"],
        icon: "gear",
        title: "Hosting + infra · llave en mano",
        desc: "Cloudflare, FastAPI, Postgres. Backups, monitoreo y rollbacks incluidos.",
        size: "w2",
      },
      {
        id: "ai-auto",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0e1e1c, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/ia-automatizaciones",
        liveLog: ["[14:50] OCR factura proveedor procesada","[14:50] Pedido clasificado · urgente","[14:51] Reposición sugerida · 14 SKUs","[14:51] Email respondido por agente IA"],
        icon: "bolt",
        title: "Automatizaciones con IA",
        desc: "Clasificación de pedidos, OCR de facturas, sugerencias de reposición.",
        tag: "IA",
        size: "w2",
      },
    ],
    bankList: ["Galicia", "Santander", "BBVA", "Mercado Pago"],
    leadMagnet: {
      h: "Pasame tu Excel de stock o ventas.",
      hAccent: "Te devuelvo el análisis en 48hs.",
      sub: "Normalizado, con KPIs, con los outliers marcados. Si lo que ves te sirve, hablamos. Si no, te quedás con el archivo.",
      cta: "Subir mi Excel",
      hint: "XLSX o CSV · hasta 25 MB · privado, no se comparte.",
    },
    wa: {
      h: "¿Listo para ver tu sistema corriendo en 30 días?",
      sub: "Agendamos una demo de 25 min. Sin pitch, sin slides — vemos tu operación actual y te muestro qué se puede automatizar primero.",
      btn: "Escribime por WhatsApp",
      phone: "+54 9 11 5383 9101",
      prefill: (s) => `Hola Sergio, vi la landing de Roker Labs y quiero saber sobre ${s || "tus sistemas"}.`,
    },
    footer: {
      tagline: "Trabajo con PyMEs argentinas que necesitan software real, no plantillas.",
      address: "Argentina · trabajando con Paraguay",
      cuit: "CUIT 20-XX-XXXX-X",
    },
  },

  PY: {
    flag: "🇵🇾",
    code: "PY",
    label: "Paraguay",
    hero: {
      eyebrowDot: "Operativo · AR + PY",
      eyebrow: "Software a medida · Roker Labs",
      h1Pre: "Sistemas que",
      h1Strike: "no se rompen los lunes",
      h1Post: "ni te dejan",
      h1Accent: "esperando un mes.",
      sub: "Software + IA + facturación SIFEN + CRM por WhatsApp. Una sola persona técnica, entrega total — hablás conmigo, decidís con vos, sin proxies.",
      cta1: "Agendar demo",
      cta2: "Ver demos",
      kpis: [
        { v: "15+", l: "años en operaciones" },
        { v: "4", l: "demos navegables" },
        { v: "AR·PY", l: "mercado dual" },
      ],
    },
    trust: {
      label: "Verticales en producción",
      items: [
        { name: "Retail electrónico", city: "AR + PY", initial: "RT", color: "rgba(220,38,38,0.40)" },
        { name: "Gastronomía premium", city: "Ciudad del Este", initial: "GA", color: "rgba(34,211,238,0.35)" },
        { name: "Distribución regional", city: "Norte AR · CDE", initial: "DR", color: "rgba(245,158,11,0.30)" },
        { name: "E-commerce + Tienda Mía", city: "Asunción", initial: "EC", color: "rgba(16,185,129,0.30)" },
      ],
      stats: [
        { v: "USD 1.8M", l: "Procesado / año" },
        { v: "99.97%", l: "Uptime POS" },
      ],
    },
    bento: {
      eyebrow: "Lo que construyo",
      h2: "Dieciséis servicios. Una sola persona. Cero intermediarios.",
      sub: "Desde el POS que corre en el mostrador hasta el agente de IA que te contesta en WhatsApp. SIFEN, Bancard y Tigo Money integrados — sin armar un Frankenstein de plugins.",
    },
    services: [
      {
        id: "pos",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #2a1810, #08080b)",
        demoUrl: "https://saborcriollo-demo.pages.dev/",
        icon: "receipt",
        title: "Sistemas POS a medida",
        desc: "Mostrador rápido, cuenta corriente, listas de precios USD/PYG, cierre de caja. Toca y vendes.",
        price: "Desde USD 1.490",
        priceNote: "Setup",
        tag: "Demo en vivo",
        size: "w3 h2",
        brand: true,
        mock: "pos",
      },
      {
        id: "dash",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0f1922, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/dashboard-comando",
        icon: "pulse",
        title: "Dashboards de gestión",
        desc: "Lo que vendiste, lo que cobraste, lo que falta. Sin Excel, sin Looker, sin lag.",
        price: "Desde USD 690",
        priceNote: "Mensual",
        size: "w3 h2",
        mock: "dash",
      },
      {
        id: "ai-wa",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #182028, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/atajo-ia",
        icon: "whatsapp",
        title: "Agente IA por WhatsApp",
        desc: "Consultá stock, generá presupuesto, derivá al humano cuando hace falta.",
        price: "USD 290",
        priceNote: "/ mes",
        tag: "IA",
        size: "w2",
        mock: "chat",
      },
      {
        id: "catalog",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1e1a2b, #08080b)",
        demoUrl: "https://carhub-demo.pages.dev/",
        icon: "cart",
        title: "Catálogos web + WhatsApp",
        desc: "El cliente arma su pedido y te llega al WhatsApp, listo para confirmar.",
        price: "USD 890",
        size: "w2",
        mock: "catalog",
      },
      // NEW PY-only services
      {
        id: "sifen",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1a1815, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/sifen-py",
        liveLog: ["[14:32] KuDE generado · CDC #34-1234","[14:33] Lote enviado a SET","[14:33] Aprobado por SET · OK","[14:33] PDF + XML enviados al cliente"],
        icon: "shield-check",
        title: "Facturación electrónica SIFEN",
        desc: "Homologación SET, KuDE, lote diario, eventos. Factura electrónica y autofactura.",
        tag: "Paraguay",
        tagPY: true,
        size: "w2",
        isNew: true,
      },
      {
        id: "billeteras",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #161d24, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/multi-billetera-py",
        icon: "wallet",
        title: "Cobros multi-billetera",
        desc: "Bancard, Tigo Money, Personal Pay, Wally. Conciliación unificada y QR único.",
        tag: "Paraguay",
        tagPY: true,
        size: "w2 h2",
        isNew: true,
      },
      {
        id: "importacion",
        cat: "infra",
        bgImage: "https://images.unsplash.com/photo-1577416412292-747c6607f055?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #15191e, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/import-cde",
        liveLog: ["[14:34] Container HBLU-3492 ingresado","[14:34] 1.420 unidades validadas","[14:35] Costo CIF + aranceles calculados","[14:35] Reexportación a BR registrada"],
        icon: "box",
        title: "Importación China + reexportación",
        desc: "Catálogo Alibaba/1688 → ficha de costos → POS → reexportación regional.",
        tag: "Paraguay",
        tagPY: true,
        size: "w2",
        isNew: true,
      },
      {
        id: "marketplaces",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1e1a2b, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/marketplaces-py",
        liveLog: ["[14:36] Tienda Mía sincronizada · 240 SKUs","[14:36] FB Marketplace · 12 mensajes","[14:37] Tutiendapy · 4 ventas nuevas","[14:37] Stock unificado a las 3 plataformas"],
        icon: "cart",
        title: "Tienda Mía · Tutiendapy · FB Mkt.",
        desc: "Publicaciones, stock y preguntas sincronizadas con tu sistema interno.",
        size: "w2",
      },
      {
        id: "ctacte",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1c1814, #08080b)",
        demoUrl: "https://fixmobile-demo.pages.dev/",
        liveLog: ["[14:40] Cliente mayorista · saldo +$ 48.500","[14:40] Pago parcial recibido · $ 18.000","[14:41] Recordatorio enviado a 3 clientes","[14:41] Mora calculada · 22 cuentas"],
        icon: "user",
        title: "Cuentas corrientes",
        desc: "Saldos en USD y PYG, cobranzas, intereses, alertas. Lo que tu cobradora necesita.",
        size: "w2",
      },
      {
        id: "listas",
        cat: "tactica",
        bgImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #131a22, #08080b)",
        demoUrl: "https://motohub-demo.pages.dev/",
        liveLog: ["[14:42] USD oficial: 1.490 · CCL: 1.612","[14:42] 142 SKUs recalculados","[14:43] Margen promedio · 38.2%","[14:43] Lista pública publicada"],
        icon: "receipt",
        title: "Listas de precios dinámicas",
        desc: "USD, costo, margen por categoría. Recalculá toda la lista en un click.",
        size: "w2",
      },
      {
        id: "migra",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #181b22, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/migra-excel",
        liveLog: ["[14:44] stock_marzo.xlsx · 8.432 filas","[14:44] 23 outliers detectados","[14:45] Base normalizada · 8.409 filas","[14:45] Reporte PDF listo · 12 páginas"],
        icon: "arrow-right",
        title: "Migraciones de Excel",
        desc: "Pasame tu planilla con 8000 SKUs. Te devuelvo la base normalizada en 48hs.",
        size: "w2",
      },
      {
        id: "soporte",
        cat: "infra",
        bgImage: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #1c1820, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/soporte-directo",
        liveLog: ["[14:46] Mensaje recibido · cliente activo","[14:46] Sergio escribiendo…","[14:47] Llamada activa · 2:34 en vivo","[14:47] Issue resuelto · cerrado"],
        icon: "lock",
        title: "Soporte directo · sin tickets",
        desc: "WhatsApp directo conmigo. Si algo se rompe, lo arreglo. Sin call center.",
        size: "w2",
      },
      {
        id: "infra",
        cat: "infra",
        bgImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0e1620, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/infra-llave-mano",
        liveLog: ["[14:48] Healthcheck · 99.99% uptime","[14:48] Postgres replicado · 0 lag","[14:49] Backup diario completado · 1.4 GB","[14:49] Cloudflare cache HIT 94.2%"],
        icon: "gear",
        title: "Hosting + infra · llave en mano",
        desc: "Cloudflare, FastAPI, Postgres. Backups, monitoreo y rollbacks incluidos.",
        size: "w2",
      },
      {
        id: "ai-auto",
        cat: "ai",
        bgImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&q=60&auto=format&fit=crop",
        bgMood: "linear-gradient(135deg, #0e1e1c, #08080b)",
        demoUrl: "https://roker-labs-demos.pages.dev/demo/ia-automatizaciones",
        liveLog: ["[14:50] OCR factura proveedor procesada","[14:50] Pedido clasificado · urgente","[14:51] Reposición sugerida · 14 SKUs","[14:51] Email respondido por agente IA"],
        icon: "bolt",
        title: "Automatizaciones con IA",
        desc: "Clasificación de pedidos, OCR de facturas, sugerencias de reposición.",
        tag: "IA",
        size: "w2",
      },
    ],
    bankList: ["Bancard", "Tigo Money", "Personal Pay", "Wally"],
    leadMagnet: {
      h: "Pasame tu Excel de stock o ventas.",
      hAccent: "Te devuelvo el análisis en 48hs.",
      sub: "Normalizado, con KPIs, con los outliers marcados. Si lo que ves te sirve, hablamos. Si no, te quedás con el archivo.",
      cta: "Subir mi Excel",
      hint: "XLSX o CSV · hasta 25 MB · privado, no se comparte.",
    },
    wa: {
      h: "¿Listo para ver tu sistema corriendo en 30 días?",
      sub: "Agendamos una demo de 25 min. Sin pitch, sin slides — vemos tu operación actual y te muestro qué se puede automatizar primero.",
      btn: "Escribime por WhatsApp",
      phone: "+54 9 11 5383 9101",
      prefill: (s) => `Hola Sergio, te escribo desde Paraguay. Vi tu landing y quiero saber sobre ${s || "tus sistemas"}.`,
    },
    footer: {
      tagline: "Trabajo con clientes en Argentina y Paraguay.",
      address: "Argentina · trabajando con Paraguay",
      cuit: "CUIT 20-XX-XXXX-X",
    },
  },
};
